version: '3.9'
services:
  app:
    build: {
      context: .,
      dockerfile: Dockerfile
    }
    volumes:
      - ..:/var/www/html:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  

  mysql:
    image: mysql
    ports:
      - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysql-data:
